### ISSUE TITLE
Spec fails under Ruby 2.1.2

### ISSUE THREAD

**Issue by loren** [freemanoid/truncator#5]
1) Truncator::UrlParser.shorten_url when URL contains query param with no value should just perform a basic truncation
     Failure/Error: Truncator::UrlParser.shorten_url(missing_param_value).should == 'https://npiregistry.cms.hhs.gov/NPPESRe...'
       expected: "https://npiregistry.cms.hhs.gov/NPPESRe..."
            got: "https://npiregistry.cms.hhs.gov/NPPESRegistry/DisplayProviderDetails.do?searchNpi=1629006051..." (using ==)
     # ./spec/url_parser_spec.rb:193:in `block (4 levels) in <top (required)>'

**Comment by freemanoid** [comment]
Fixed now.
